<?php

/**
 * Project Euler Problem 2:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 *		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * The sum of the even-valued terms whose values do not exceed one hundred would
 * be 44 (2 + 8 + 34)
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * Problem: https://projecteuler.net/problem=2
 * Solution: https://github.com/potherca-blog/ProjectEuler/blob/master/src/PHP/Solutions/Problem002.php
 * Live code: https://ideone.com/Sur5V4
 */
namespace Potherca\ProjectEuler\Solutions\Problem002
{
    use Potherca\ProjectEuler\Calculators\FibonacciCalculator as Calculator;

    $limit = 4000000;

    $solution = (new Calculator())->getSumOfEvenTermsBelow($limit);
    
    echo $solution;
}
